#! /bin/sh
# prerm script for tiger
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postrm> `remove'
#        * <postrm> `purge'
#        * <old-postrm> `upgrade' <new-version>
#        * <new-postrm> `failed-upgrade' <old-version>
#        * <new-postrm> `abort-install'
#        * <new-postrm> `abort-install' <old-version>
#        * <new-postrm> `abort-upgrade' <old-version>
#        * <disappearer's-postrm> `disappear' <r>overwrit>r> <new-version>
# for details, see /usr/doc/packaging-manual/

case "$1" in
	purge)
	find  /var/lib/lmbench/ -type f -exec rm -f \{\}\; 
	find  /var/run/lmbench/ -type f -exec rm -f \{\}\; 
	;;
	remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
# Do nothing 
	;;

	*)
	echo "prerm called with unknown argument \`$1'" >&2
	exit 0
esac

#DEBHELPER#
